# Generated by Django 2.2.10 on 2020-08-16 08:04

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cetegories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Category Name:- ')),
                ('url', models.SlugField(verbose_name='Category URL:- ')),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', froala_editor.fields.FroalaField()),
            ],
        ),
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Page Title:- ')),
                ('url', models.SlugField(verbose_name='Tool URL:- ')),
                ('content', froala_editor.fields.FroalaField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Page',
            },
        ),
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('convertFrom', models.CharField(max_length=50, verbose_name='Convert From:- ')),
                ('convertTo', models.CharField(max_length=50, verbose_name='Convert To:- ')),
                ('url', models.SlugField(verbose_name='Tool URL:- ')),
                ('viceVerca', models.SlugField(blank=True, null=True, verbose_name='Reverse URL:- ')),
                ('description', models.TextField(max_length=160, verbose_name='Meta Description:- ')),
                ('javascript', models.TextField(max_length=500, verbose_name='Java Script Code :- ')),
                ('keywords', models.TextField(max_length=100, verbose_name='Meta Keywords:- ')),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('content', froala_editor.fields.FroalaField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='converter.Cetegories')),
            ],
            options={
                'verbose_name_plural': 'Tool',
            },
        ),
    ]
