# Generated by Django 2.2.10 on 2020-08-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0002_ads'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adsense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad1', models.TextField(max_length=200, verbose_name='Auto Ad:- ')),
                ('ad2', models.TextField(max_length=200, verbose_name='Vertical Ad:- ')),
                ('ad3', models.TextField(max_length=200, verbose_name='Rectangle Ad:- ')),
                ('ad4', models.TextField(max_length=200, verbose_name='Text Link Ad:- ')),
            ],
        ),
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belowHead', models.TextField(max_length=300, verbose_name='Paste the code below <head> tag:- ')),
                ('belowBody', models.TextField(max_length=300, verbose_name='Paste the code below <body> tag:- ')),
            ],
        ),
    ]
