# Generated by Django 3.1.1 on 2020-12-12 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('converter', '0003_adsense_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField(blank=True, max_length=200, null=True, verbose_name='Header Ad:- ')),
                ('sidebar1', models.TextField(blank=True, max_length=200, null=True, verbose_name='First Sidebard Ad:- ')),
                ('sidebar2', models.TextField(blank=True, max_length=200, null=True, verbose_name='Second Sidebar Ad:- ')),
                ('inArticle1', models.TextField(blank=True, max_length=200, null=True, verbose_name='In Article Ad:- ')),
                ('inArticle2', models.TextField(blank=True, max_length=200, null=True, verbose_name='In Article Ad:- ')),
                ('inArticle3', models.TextField(blank=True, max_length=200, null=True, verbose_name='In Article Ad:- ')),
                ('status', models.IntegerField(choices=[(0, 'Enable'), (1, 'Disable')], default=0)),
            ],
            options={
                'verbose_name_plural': 'Advertisement Ad Code',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='Post Title:- ')),
                ('tumbnail', models.ImageField(upload_to='', verbose_name='Featured Image:-')),
                ('description', models.TextField(max_length=160, verbose_name='Description:- ')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Post URL:-')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Online Converter Blog',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Adsense',
        ),
        migrations.AlterModelOptions(
            name='pages',
            options={'verbose_name_plural': 'Online Converter Page'},
        ),
        migrations.AlterModelOptions(
            name='tools',
            options={'verbose_name_plural': 'Online Converter Tools Section'},
        ),
    ]
