# Generated by Django 3.1.1 on 2020-12-15 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_auto_20201212_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='converter.cetegories'),
            preserve_default=False,
        ),
    ]
