
# Generated by Django 3.1.4 on 2021-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name:- ')),
                ('email', models.CharField(max_length=50, verbose_name='User Email:- ')),
                ('query', models.CharField(max_length=50, verbose_name='User Message:- ')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Contact',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='tools',
            name='one_unit_to_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='One unit to value:- '),
        ),
        migrations.AddField(
            model_name='tools',
            name='unit_from',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit from:- '),
        ),
        migrations.AddField(
            model_name='tools',
            name='unit_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit to:- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta Description:- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='javascript',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Java Script Code :- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='keywords',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Meta Keywords:- '),
        ),
    ]

# Generated by Django 3.1.4 on 2021-11-15 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='User Name:- ')),
                ('email', models.CharField(max_length=50, verbose_name='User Email:- ')),
                ('query', models.CharField(max_length=50, verbose_name='User Message:- ')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'User Contact',
                'ordering': ['-created_on'],
            },
        ),
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.DeleteModel(
            name='Pages',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
        migrations.AddField(
            model_name='tools',
            name='one_unit_to_value',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=15, verbose_name='One unit to value:- '),
        ),
        migrations.AddField(
            model_name='tools',
            name='unit_from',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit from:- '),
        ),
        migrations.AddField(
            model_name='tools',
            name='unit_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Unit to:- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='description',
            field=models.TextField(blank=True, max_length=160, null=True, verbose_name='Meta Description:- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='javascript',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Java Script Code :- '),
        ),
        migrations.AlterField(
            model_name='tools',
            name='keywords',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Meta Keywords:- '),
        ),
    ]

