
from django.urls import path
from converter.views import *
from .sitemap import StaticSitemap
from django.contrib.sitemaps.views import sitemap
from .hash_generator import *

sitemaps = {
    'static':StaticSitemap #add StaticSitemap to the dictionary
}
handler404 = 'converter.views.error_404'
urlpatterns = [
    path('', Index2, name = 'Index2'),
    # path('home', Index2, name = 'Index2'),
    path('online-character-counter', charCount, name = 'charCount'),
    path('online-password-generator', Password, name = 'Password'),
    path('online-word-counter', wordCount, name = 'wordCount'),
    path('total-words', totalWord, name = 'totalWord'),
    path('uppercase-to-lowercase-online-converter', lowerCase, name = 'lowerCase'),
    path('lowercase-to-uppercase-online-converter', upperCase, name = 'upperCase'),
    path('online-string-reverse', stringReverse, name = 'stringReverse'),
    path('online-word-reverse', wordsReverse, name = 'wordsReverse'),
    path('online-titlecase-converter', titleCase1, name = 'titleCase1'),
    path('title-case', titleCase2, name = 'titleCase2'),
    path('capitalize-first-letter-of-string', Capitalize, name = 'Capitalize'),
    path('binary-to-decimal-online-converter', bintoDec, name = 'bintoDec'),
    path('binary-to-decimal', bintoDec2, name = 'bintoDec2'),
    path('binary-to-octal-online-converter', bintoOct, name = 'bintoOct'),
    path('binary-to-octal', bintoOct2, name = 'bintoOct2'),
    path('binary-to-hexadecimal-online-converter', bintoHex, name = 'bintoHex'),
    path('binary-to-hexadecimal', bintoHex2, name = 'bintoHex2'),
    path('octal-to-binary-online-converter', octtoBin, name = 'octtoBin'),
    path('octal-to-binary', octtoBin2, name = 'octtoBin2'),
    path('octal-to-decimal-online-converter', octtoDec, name = 'octtoDec'),
    path('octal-to-decimal', octtoDec2, name = 'octtoDec2'),
    path('octal-to-hexadecimal-online-converter', octtoHex, name = 'octtoHex'),
    path('octal-to-hexadecimal', octtoHex2, name = 'octtoHex2'),
    path('hexadecimal-to-decimal-online-converter', hextoDec, name = 'hextoDec'),
    path('hexadecimal-to-decimal', hextoDec2, name = 'hextoDec2'),
    path('hexadecimal-to-binary-online-converter', hextoBin, name = 'hextoBin'),
    path('hexadecimal-to-binary', hextoBin2, name = 'hextoBin2'),
    path('hexadecimal-to-octal-online-converter', hextoOct, name = 'hextoOct'),
    path('hexadecimal-to-octal', hextoOct2, name = 'hextoOct2'),
    path('decimal-to-binary-online-converter', dectoBin, name = 'dectoBin'),
    path('decimal-to-binary', dectoBin2, name = 'dectoBin2'),
    path('decimal-to-octal-online-converter', dectoOct, name = 'dectoOct'),
    path('decimal-to-octal', dectoOct2, name = 'dectoOct2'),
    path('decimal-to-hexadecimal-online-converter', dectoHex, name = 'dectoHex'),
    path('decimal-to-hexadecimal', dectoHex2, name = 'dectoHex2'),
    path('online-html-encoder-tool', htmlEncode, name = 'htmlEncode'),
    path('online-html-decoder-tool', htmlDecode, name = 'htmlDecode'),
    path('base64-encoder-online', base64Encode, name = 'base64Encode'),
    path('base64-decoder-online', base64Decode, name = 'base64Decode'),
    path('string-to-binary-online-converter', stringtoBin, name = 'stringtoBin'),
    path('string-to-binary', stringtoBin2.as_view(), name = 'stringtoBin2'),
    path('binary-to-string-online-converter', bintoString, name = 'bintoString'),
    path('binary-to-string', bintoString2, name = 'bintoString2'),
    path('string-to-hex-online-converter', stringtoHex, name = 'stringtoHex'),
    path('string-to-hex', stringtoHex2, name = 'stringtoHex2'),
    path('hex-to-string-online-converter', hextoString, name = 'hextoString'),
    path('hex-to-string', hextoString2, name = 'hextoString2'),
    path('url-encoder-tool', urlEncode, name = 'urlEncode'),
    path('url-encoder', urlEncode2, name = 'urlEncode2'),
    path('url-decoder-tool', urlDecode, name = 'urlDecode'),
    path('url-decoder', urlDecode2, name = 'urlDecode2'),

    # pages URL
    path('privacy-policy', PrivacyPolicy, name = 'PrivacyPolicy'),
    path('terms-and-condition', TermsCondition, name = 'TermsCondition'),
    path('contact-us', ContactUs, name = 'ContactUs'),
    path('about', AboutUs, name = 'AboutUs'),

 
    #Temprature
    path('celsius-to-fahrenheit-online-converter', celtoFah, name = 'celtoFah'),
    path('celsius-to-kelvin-online-converter', celtoKel, name = 'celtoKel'),
    path('celsius-to-rankine-online-converter', celtoRank, name = 'celtoRank'),
    path('fahrenheit-to-celsius-online-converter', fahtoCel, name = 'fahtoCel'),
    path('fahrenheit-to-kelvin-online-converter', fahtoKel, name = 'fahtoKel'),
    path('fahrenheit-to-rankine-online-converter', fahtoRank, name = 'fahtoRank'),
    path('kelvin-to-celsius-online-converter', keltoCel, name = 'keltoCel'),
    path('kelvin-to-fahrenheit-online-converter', keltoFah, name = 'keltoFah'),
    path('kelvin-to-rankine-online-converter', keltoRank, name = 'keltoRank'),
    path('rankine-to-celsius-online-converter', ranktoCel, name = 'ranktoCel'),
    path('rankine-to-fahrenheit-online-converter', ranktoFah, name = 'ranktoFah'),
    path('rankine-to-kelvin-online-converter', ranktoKel, name = 'ranktoKel'),
    path('online-string-converter-tools', stringConverter, name = 'stringConverter'),
    path('online-number-converter-tools', numberConverter, name = 'numberConverter'),
    path('online-temprature-converter-tools', tempConverter, name = 'tempConverter'),
    path('blog', BlogList.as_view()),
    path('page/<str:slug>', Pages, name = 'Pages'),
    path('converter/<str:slug>', Converter, name = 'Converter'),
    path('<str:conType>/<str:slug>', converterTool, name = 'converterTool'),

    #hash value urls
    path('online-hash-generator-tools', all_hash_generator_page, name = 'all_hash_generator_page'),
    path('online-md5-hash-generator', md5_hash_generator, name = 'md5_hash_generator'),
    path('online-sha224-hash-generator', sha224_hash_generator, name = 'sha224_hash_generator'),
    path('online-md4-hash-generator', md4_hash_generator, name = 'md4_hash_generator'),
    path('online-sha1-hash-generator', sha1_hash_generator, name = 'sha1_hash_generator'),
    path('online-shake-128-hash-generator', shake_128_hash_generator, name = 'shake_128_hash_generator'),
    path('online-whirlpool-hash-generator', whirlpool_hash_generator, name = 'whirlpool_hash_generator'),
    path('online-sm3-hash-generator', sm3_hash_generator, name = 'sm3_hash_generator'),
    path('online-sha384-hash-generator', sha384_hash_generator, name = 'sha384_hash_generator'),
    path('online-sha512_256-hash-generator', sha512_256_hash_generator, name = 'sha512_256_hash_generator'),
    path('online-md5-sha1-hash-generator', md5_sha1_hash_generator, name = 'md5_sha1_hash_generator'),
    path('online-mdc2-hash-generator', mdc2_hash_generator, name = 'mdc2_hash_generator'),
    path('online-sha512-224-hash-generator', sha512_224_hash_generator, name = 'sha512_224_hash_generator'),
    path('online-blake2b-hash-generator', blake2b_hash_generator, name = 'blake2b_hash_generator'),
    path('online-sha3-224-hash-generator', sha3_224_hash_generator, name = 'sha3_224_hash_generator'),
    path('online-sha512-hash-generator', sha512_hash_generator, name = 'sha512_hash_generator'),
    path('online-shake-256-hash-generator', shake_256_hash_generator, name = 'shake_256_hash_generator'),
    path('online-blake2s-hash-generator', blake2s_hash_generator, name = 'blake2s_hash_generator'),
    path('online-sha3-512-hash-generator', sha3_512_hash_generator, name = 'sha3_512_hash_generator'),
    path('online-ripemd160-hash-generator', ripemd160_hash_generator, name = 'ripemd160_hash_generator'),
    path('online-sha3-256-hash-generator', sha3_256_hash_generator, name = 'sha3_256_hash_generator'),
    path('online-sha256-hash-generator', sha256_hash_generator, name = 'sha256_hash_generator'),
    path('online-sha3-384-hash-generator', sha3_384_hash_generator, name = 'sha3_384_hash_generator'),
    path('generate-hash-value', HashValueGenerator.as_view(), name = 'HashValueGenerator'),

    
    path('ads.txt', Adstxt, name = 'Adstxt'),
    path('robots.txt', robots_txt, name = 'robots_txt'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
    
]
